version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  assignees:
  - freddydumont
  ignore:
  - dependency-name: theme-ui
    versions:
    - 0.6.0
    - 0.6.0-alpha.7
    - 0.6.0-canary.1544.3ce24759664e3c638354903f9eebb194f2bae7ec.0
    - 0.6.0-canary.1544.5359f8a1e408a4dfeb74a9ae39688270286e534a.0
    - 0.6.1
    - 0.6.2
    - 0.7.0
    - 0.7.2
    - 0.7.3
    - 0.7.4
  - dependency-name: "@theme-ui/presets"
    versions:
    - 0.6.0
    - 0.6.0-alpha.6
    - 0.6.0-alpha.7
    - 0.6.0-canary.1544.5359f8a1e408a4dfeb74a9ae39688270286e534a.0
    - 0.6.1
    - 0.6.2
    - 0.7.0
    - 0.7.2
    - 0.7.3
    - 0.7.4
  - dependency-name: "@theme-ui/style-guide"
    versions:
    - 0.6.0
    - 0.6.0-alpha.7
    - 0.6.0-canary.1544.5359f8a1e408a4dfeb74a9ae39688270286e534a.0
    - 0.6.1
    - 0.6.2
    - 0.7.0
    - 0.7.2
    - 0.7.3
    - 0.7.4
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: cypress
    versions:
    - 7.1.0
  - dependency-name: next
    versions:
    - 10.1.2
    - 10.1.3
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
