version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '11:00'
    open-pull-requests-limit: 12
    assignees:
      - freddydumont
