name: Test with Jest and Cypress
on: [push]
jobs:
  yarn-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:3000'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: artifacts-${{ github.run_id }}
          path: |
            ${{ github.workspace }}/cypress/screenshots
            ${{ github.workspace }}/cypress/videos
